spring.application.name=letramento-digital

# Database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/letramento_db
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Hibernate configuration
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#spring.jpa.properties.hibernate.type.json_format_mapper=org.hibernate.type.format.jackson.Jackson3JsonFormatMapper
# Define o Jackson 3 customizado como o FormatMapper padrão para colunas JSON/JSONB
spring.jpa.properties.hibernate.type.json_format_mapper=com.projeto.tcc.letramento.config.Jackson3FormatMapper
# Configuração local para ativação do repositório OAuth2 Client
spring.security.oauth2.client.registration.google.client-id=mock-local-client-id-tcc.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=mock-local-client-secret-123456