spring.application.name=letramento-digital

# Database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/letramento_db
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Hibernate configuration
spring.jpa.hibernate.ddl-auto=validate

# Show SQL statements in the console (logs)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
